// export const colorPrimary = '#00d8c9'
export const colorPrimary = '#00e9ec'
export const colorSecondary = '#202833'
export const colorTertiary = '#0b0c10'
export const colorFour = '#845DC0'
export const white = '#fff'
